version: '3'
services:
  db:
    image: mariadb:10.3
    container_name: dbService
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: telkom
      MYSQL_USER: user
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_ROOT_HOST: "%"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
  be:
    build: ./backend
    container_name: backEndService
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - db
    links:
      - db
  fe:
    container_name: frontEndService
    build: ./frontend
    ports:
      - '80:80'
    depends_on:
      - be
    restart: always
  phpmyadmin:
    container_name: phpMyAdminService
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
volumes:
  db_data: