version: '3'
services:
  db:
    image: mariadb:10.2
    container_name: dbService
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: telkom
      MYSQL_USER: user
      MYSQL_PASSWORD: P@ssw0rd
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3306:3306
  be:
    build: ./backend
    container_name: backEndService
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - db
    links:
      - db